import React from "react";

// ── Modal Styles (shared) ──────────────────────────────
export const modalStyles: Record<string, React.CSSProperties> = {
  overlay: {
    position: "fixed",
    top: 0, left: 0, right: 0, bottom: 0,
    background: "rgba(0, 0, 0, 0.85)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  container: {
    background: "#1a1a2e",
    borderRadius: 12,
    maxWidth: "92vw",
    maxHeight: "92vh",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    boxShadow: "0 8px 40px rgba(0,0,0,0.5)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 16px",
    borderBottom: "1px solid #333",
    color: "#eee",
  },
  filename: { flex: 1, fontSize: 15, fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  fileinfo: { fontSize: 12, color: "#999", whiteSpace: "nowrap" },
  closeBtn: { background: "none", border: "none", color: "#ccc", fontSize: 20, cursor: "pointer", padding: "4px 8px", borderRadius: 4, lineHeight: 1 },
  content: { position: "relative", display: "flex", alignItems: "center", justifyContent: "center", flex: 1, overflow: "hidden", minHeight: 200 },
  video: { maxWidth: "88vw", maxHeight: "75vh", outline: "none", borderRadius: 4 },
  audioWrapper: { display: "flex", flexDirection: "column", alignItems: "center", gap: 24, padding: "48px 64px" },
  audio: { width: 400, maxWidth: "80vw" },
  image: { maxWidth: "88vw", maxHeight: "75vh", objectFit: "contain", borderRadius: 4 },
  navArrow: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(255,255,255,0.15)",
    border: "none",
    color: "#fff",
    fontSize: 24,
    cursor: "pointer",
    padding: "16px 12px",
    borderRadius: 8,
    zIndex: 10,
    transition: "background 150ms",
  },
  footer: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 16px", borderTop: "1px solid #333", color: "#aaa", fontSize: 13 },
  counter: { color: "#888" },
  downloadLink: { color: "#6cb4ee", textDecoration: "none", fontSize: 13, display: "inline-flex", alignItems: "center" },
};
